name: todo_list_bloc
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_form_builder: ^9.3.0
  fluttertoast: ^8.2.6
  form_builder_validators: ^11.0.0
  go_router: ^14.2.1
  intl: ^0.19.0
  uuid: ^4.4.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
